export { default as Header } from './Header'
export { default as Categories } from './Categories'
export { default as CategoryCard } from './CategoryCard'
export { default as Featured } from './Featured'
export { default as About } from './About'
export { default as Cart } from './Cart'
export { default as Footer } from './Footer'
export { default as ScrollToTop } from './ScrollToTop'
